
/**
 * Detects if an Excel item description targets a specific spatial zone.
 * e.g., "Tabique Sala" -> "SALA"
 * e.g., "Cielo falso Bodega" -> "BODEGA"
 */
export function extractZoneIntent(description: string): string | null {
    if (!description) return null;
    const normalized = description.toUpperCase();

    // Mapping of keywords to canonical Zone Names
    // Note: These should match the names generated by your SpatialGraph (which come from DXF text)
    const keywords: Record<string, string> = {
        'SALA': 'SALA',
        'ESTAR': 'SALA', // "Estar" often implies Living/Sala
        'COMEDOR': 'COMEDOR',
        'COCINA': 'COCINA',
        'BODEGA': 'BODEGA',
        'DORMITORIO': 'DORMITORIO',
        'DORM': 'DORMITORIO',
        'BAÑO': 'BAÑO',
        'BANO': 'BAÑO',
        'LOGGIA': 'LOGGIA',
        'LOGIA': 'LOGGIA',
        'PASILLO': 'PASILLO',
        'HALL': 'HALL',
        'OFICINA': 'OFICINA',
        'RECEPCION': 'RECEPCION',
        'REUNIONES': 'REUNIONES'
    };

    // Iterate and find first match
    // Prioritize longer matches if necessary, but here simple keyword scan works
    for (const [key, zone] of Object.entries(keywords)) {
        // Use word boundary to avoid partial matches (e.g. "SALADA" matching "SALA")
        const regex = new RegExp(`\\b${key}\\b`, 'i');
        if (regex.test(normalized)) {
            return zone;
        }
    }

    return null;
}
